image: python:3.11

pipelines:
  default:
    - step:
        name: Test
        script:
          - apt install imagemagick
          - pip install -r requirements.txt
          - python -m unittest
