image: python:3.11

pipelines:
  default:
    - step:
        name: Test
        script:
          - apt update && apt install -y libvips-dev
          - pip install pyvips rawpy pillow tqdm
          - python -m unittest
