image: python:3.11

pipelines:
  default:
    - step:
        name: Test
        script:
          - apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
          - pip install -r requirements.txt
          - python -m unittest
